description: a description   #deve cambiare a ogni avvio

outputs:
  - type: mqtt  
    host: localhost
    port: 1883
    topic: "/mytopic/${PRODUCER_ID}" 
    frequency: 2
    frequency_count: 500
    

docker_config:
  image: finalimage
  docker_net: bigdataproject_bigdata_net
  kafka_broker: "broker:9092"
  input_topic: "temperature_input"
  output_topic: "temperature_output"
  keep-alive-ms: 1
  status: "OK"


producers:
  - id: sens_temp_1
    type: "temperature_sensor"
    data:
      name: "TM-873"
      fw_version: "1.0.0v1"
      temperature: "$_random.uniform(10.1, 25.5)"
      status: "OK"
  
  - id: sens_temp_2
    type: "docker_sensor"
    data:
      name: "TM-874"
      fw_version: "1.0.0v1"
      status: "OK"
   

